### PR TITLE
Added CC 2015

### PR DESCRIPTION
**Pull request by grefel**

### CODE REVIEW

**Comment by vamitul** [comment]
Does it work on OSX also?

**Comment by grefel** [comment]
Only Windows to test - sorry.

**Comment by vamitul** [comment]
Cool, I'll merge it after i get CC2015 up and running on my mac. 
Thank you for the help and thank you for the API website (it is the first pinned tab in my browser).
Any idea on how to turn it into a sublime extension? :wink:

**Comment by grefel** [comment]
Have you talked to Trevor regarding his API for Sublimetext? https://forums.adobe.com/message/7273686#7273686 He will send it to me and I can't wait testing it. If you have not tested it yet, just ask him. If you've tested already and aren't happy with the solution we can talk about a better one :-)

**Comment by grefel** [comment]
Hey Vamitul, can you send me an e-Mail gregor.fellenz [ at ] publishingx.de , I would like to talk to Trevor and you about code completion in sublime text.

**Pull request merged**
